/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Heading = string;
export type HeroBanner = string;
export type SearchURL = string;
export type BrowseByCategoryTitle = string;
export type Thumbnail = string;
export type Title = string;
export type Url = string;
export type CategoriesItems = {
  thumbnail?: Thumbnail;
  title?: Title;
  url?: Url;
  [k: string]: unknown;
}[];

export interface HomeJson {
  heading?: Heading;
  heroBanner?: HeroBanner;
  searchURL?: SearchURL;
  browseByCategoryTitle?: BrowseByCategoryTitle;
  categoriesItems?: CategoriesItems;
  [k: string]: unknown;
}
