/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SearchPlaceholder = string;
export type SearchButton = string;
export type SummaryPage = string;
export type DetailPage = string;
export type ResultsFor = string;
export type Displaying = string;
export type Of = string;
export type Next = string;
export type Previous = string;
export type RecordPerPage = string;
export type NoOptionsAvailable = string;
export type SortBy = string;
export type FilterBy = string;
export type Bookmark = string;
export type Home = string;
export type Copy = string;
export type Print = string;
export type Save = string;
export type NoMediaFound = string;
export type SelectRecordsNumber = string;
export type Grid = string;
export type List = string;
export type Camera = string;
export type Books = string;
export type Audio = string;
export type Video = string;
export type RsvpCancellationMessage = string;

export interface MessageJson {
  searchPlaceholder?: SearchPlaceholder;
  searchButton?: SearchButton;
  summaryPage?: SummaryPage;
  detailPage?: DetailPage;
  resultsFor?: ResultsFor;
  displaying?: Displaying;
  of?: Of;
  next?: Next;
  previous?: Previous;
  recordPerPage?: RecordPerPage;
  noOptionsAvailable?: NoOptionsAvailable;
  sortBy?: SortBy;
  filterBy?: FilterBy;
  bookmark?: Bookmark;
  home?: Home;
  copy?: Copy;
  print?: Print;
  save?: Save;
  noMediaFound?: NoMediaFound;
  selectRecordsNumber?: SelectRecordsNumber;
  grid?: Grid;
  list?: List;
  camera?: Camera;
  books?: Books;
  audio?: Audio;
  video?: Video;
  rsvpCancellationMessage?: RsvpCancellationMessage;
  [k: string]: unknown;
}
