/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type ShowButton = boolean;
export type ButtonText = string;
export type ButtonLink = string;
export type Title1 = string;
export type Subtitle1 = string;
export type ShowButton1 = boolean;
export type ButtonText1 = string;
export type ButtonLink1 = string;
export type Title2 = string;
export type Subtitle2 = string;
export type ShowButton2 = boolean;
export type ButtonText2 = string;
export type ButtonLink2 = string;
export type Title3 = string;
export type Subtitle3 = string;
export type ShowButton3 = boolean;
export type ButtonText3 = string;
export type ButtonLink3 = string;
export type Title4 = string;
export type Subtitle4 = string;
export type ShowButton4 = boolean;
export type ButtonText4 = string;
export type ButtonLink4 = string;
export type Title5 = string;
export type Subtitle5 = string;
export type ShowButton5 = boolean;
export type Title6 = string;
export type Subtitle6 = string;
export type ShowButton6 = boolean;
export type ButtonText5 = string;
export type ButtonLink5 = string;
export type Title7 = string;
export type Subtitle7 = string;
export type ShowButton7 = boolean;

export interface RsvpJson {
  confirmLandingExpired?: ConfirmLandingExpired;
  confirmLandingInList?: ConfirmLandingInList;
  confirmLandingFullEvent?: ConfirmLandingFullEvent;
  confirmLandingOutDate?: ConfirmLandingOutDate;
  confirmLandingInvalid?: ConfirmLandingInvalid;
  confirmLandingSuccess?: ConfirmLandingSuccess;
  cancelLandingNotIntheList?: CancelLandingNotIntheList;
  cancelLandingSuccess?: CancelLandingSuccess;
  [k: string]: unknown;
}
export interface ConfirmLandingExpired {
  title?: Title;
  subtitle?: Subtitle;
  showButton?: ShowButton;
  buttonText?: ButtonText;
  buttonLink?: ButtonLink;
  [k: string]: unknown;
}
export interface ConfirmLandingInList {
  title?: Title1;
  subtitle?: Subtitle1;
  showButton?: ShowButton1;
  buttonText?: ButtonText1;
  buttonLink?: ButtonLink1;
  [k: string]: unknown;
}
export interface ConfirmLandingFullEvent {
  title?: Title2;
  subtitle?: Subtitle2;
  showButton?: ShowButton2;
  buttonText?: ButtonText2;
  buttonLink?: ButtonLink2;
  [k: string]: unknown;
}
export interface ConfirmLandingOutDate {
  title?: Title3;
  subtitle?: Subtitle3;
  showButton?: ShowButton3;
  buttonText?: ButtonText3;
  buttonLink?: ButtonLink3;
  [k: string]: unknown;
}
export interface ConfirmLandingInvalid {
  title?: Title4;
  subtitle?: Subtitle4;
  showButton?: ShowButton4;
  buttonText?: ButtonText4;
  buttonLink?: ButtonLink4;
  [k: string]: unknown;
}
export interface ConfirmLandingSuccess {
  title?: Title5;
  subtitle?: Subtitle5;
  showButton?: ShowButton5;
  [k: string]: unknown;
}
export interface CancelLandingNotIntheList {
  title?: Title6;
  subtitle?: Subtitle6;
  showButton?: ShowButton6;
  buttonText?: ButtonText5;
  buttonLink?: ButtonLink5;
  [k: string]: unknown;
}
export interface CancelLandingSuccess {
  title?: Title7;
  subtitle?: Subtitle7;
  showButton?: ShowButton7;
  [k: string]: unknown;
}
